config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD
  get 'questions/index'

  get 'questions/create'

  post 'ask' => 'questions#create'
  
=======
  devise_for :experts
>>>>>>> feat/expertmodel
  resources :tickets
  devise_for :users
  root 'home#index'

<<<<<<< HEAD
  get '/dashboard', to: 'expert_dashboard#index'

=======

   
>>>>>>> feat/expertmodel

end

app/models/expert.rb
class Expert < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tickets
  validates :email, presence: true, uniqueness: true
        validates :first_name, presence: true
        validates :last_name, presence: true
 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters

    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :child_age_group, :child_gender, :password, :password_confirmation, :specialty) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:first_name, :last_name, :email, :child_age_group, :child_gender, :password, :password_confirmation) }

  end
end

app/controllers/expert_dashboard_controller.rb
class ExpertDashboardController < ApplicationController

  def index
    @tickets = Ticket.all
  end

end

app/controllers/experts/registrations_controller.rb
class Admins::RegistrationsController < Devise::RegistrationsController
  # disable default no_authentication action
  skip_before_action :require_no_authentication, only: [:new, :create, :cancel]
  # now we need admin to register new admin
  prepend_before_action :authenticate_scope!, only: [:new, :create, :cancel]

  protected

  def sign_up(resource_name, resoure)
    # just overwrite the default one
    # to prevent auto sign in as the new sign up
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @ticket = Ticket.new
  end

  private

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
  end

  def create
    @ticket = Ticket.new(ticket_params)
    @user = User.new(first_name: "Guest", last_name: "User", email: "guest-#{Time.now.to_i}@email.com")
    @user.save!(:validate => false)

    @ticket.user_id = @user.id
    @ticket.save!

    session[:guest_user_id] = @user.id

    if current_user == nil
      current_user = @user
    end

    redirect_to root_path
  end

  private

  def ticket_params
    params.require(:ticket).permit(:subject, :body, :user_id)
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = current_user.tickets.all
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = current_user.tickets.build
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = current_user.tickets.build(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:subject, :body, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expert_dashboard_helper.rb
module ExpertDashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/expert_dashboard/index.html.erb
<div class="container">

<div class="row">
  <div class="col-lg-10">

<table class="table table-striped table-hover table-bordered">
     <thead>
       <tr>
         <th>Subject</th>
         <th>Message</th>
         <th>Creator</th>
         <th>View</th>
       </tr>
     </thead>
     <tbody>
       <% @tickets.each do |ticket| %>
       <tr>
         <td><%= ticket.subject %></td>
         <td><%= ticket.body %></td>
         <td><%= "#{ticket.user.first_name}" "#{ticket.user.last_name}" %></td>
         <td><%= link_to "View", ticket_path(ticket) %></td>
       </tr>
        <% end %>
     </tbody>
   </table>

</div>
</div>

</div>

app/views/experts/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/home/index.html.erb
<div class="jumbotron">
  <div class="container">
    <h1 style="text-align: center;">Reach A Pro</h1>
    <p style="text-align: center;">A network of pros here to help you and your baby...</p>
    <%= simple_form_for @ticket, url: ask_path, html: {method: :post} do |f| %>
      <div class="row">
        <div class="">
          <div class="center-block form-inline">
            <%= f.error_notification %>
            <%= f.input :body, placeholder: 'Got a baby? Got a question?', input_html: {class: "input-lg"}, label: false  %>
            <%= f.button :submit, "Ask!", class: "btn btn-lg btn-success" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>


<div class="container">
  <h1>Testimonials</h1>

  <div class="row">
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Mary N. - Peoria, Il.</h3>
        </div>
        <div class="panel-body">
          <p>"Reach A Pro sure saved the day for me and my baby! What would I have done without Reach A Pro?"</p>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Shirley T. - Busco, SC.</h3>
        </div>
        <div class="panel-body">
          <p>"Ya'll plain won't believe all the know how and expertice these pros got! Clean'd my baby up right."</p><br />
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Curtis S. - San Onofree, CA</h3>
        </div>
        <div class="panel-body">
          <p>"I don't have a baby yet, but when I do, I'll be sure to use Reach A Pro! Gee I can't wait for a baby..."</p><br />
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ReachAPro</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <!-- Navigation -->
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Home", root_path, class: "navbar-brand" %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to "Dashboard", dashboard_path %></li>
          <li><%= link_to "Link Two", "#" %></li>
          <!-- <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
          <li><a href="#">Link</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li> -->
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li>
              <%= link_to "Edit Profile", edit_user_registration_path %>
            </li>
            <li>
              <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
            </li>
          <% else %>
            <li>
              <%= link_to "Sign Up", new_user_registration_path %>
            </li>
            <li>
              <%= link_to "Log In", new_user_session_path %>
            </li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <%= yield %>

  <footer class="footer">
    <div class="container">
      <div class="row">
        <div class="col-md-4 col-md-offset-4">
          <h5 style="text-align: center;">Copyright &copy; Reach-A-Pro Public Holdings Ltd.</h5>
        </div>
      </div>
    </div>
  </footer>
</body>
</html>

app/views/questions/create.html.erb
<h1>Questions#create</h1>
<p>Find me in app/views/questions/create.html.erb</p>

app/views/questions/index.html.erb
<h1>Questions#index</h1>
<p>Find me in app/views/questions/index.html.erb</p>

app/views/tickets/_form.html.erb
<%= simple_form_for(@ticket) do |f| %>
  <%= f.error_notification %>

    <%= f.input :subject %>
    <%= f.input :body %>

    <%= f.button :submit %>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form' %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tickets</h1>

<table>
  <thead>
    <tr>
      <th>Subject</th>
      <th>Body</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.subject %></td>
        <td><%= ticket.body %></td>
        <td><%= "#{ticket.user.first_name} #{ticket.user.last_name}" %></td>
        <td><%= link_to 'Show', ticket %></td>
        <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
        <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticket', new_ticket_path %>

app/views/tickets/new.html.erb
<h1>New Ticket</h1>

<%= render 'form' %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subject:</strong>
  <%= @ticket.subject %>
</p>

<p>
  <strong>Body:</strong>
  <%= @ticket.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @ticket.user %>
</p>

<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>